# Netlify configuration for FSO Project Hub Frontend

[build]
  # Build command
  command = "cd frontend && yarn install && yarn build"
  
  # Directory with the static files
  publish = "frontend/build"
  
  # Node version
  environment = { NODE_VERSION = "20" }

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (add these in Netlify UI)
# REACT_APP_BACKEND_URL = "your-backend-api-url"
